version: "3"

services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    restart: unless-stopped
    environment:
      - DOCKER_MODS=linuxserver/mods:code-server-zsh
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SUDO_PASSWORD_FILE=/run/secrets/code_password
      - PROXY_DOMAIN=code-server.${DOMAIN}
    volumes:
      - ./data:/config
      - sync:${HOME}/Sync
      - ${HOME}/.oh-my-zsh:/config/.oh-my-zsh
      - ${HOME}/.zshrc:/config/.zshrc
    ports:
      - 8443:8443
    secrets:
      - code_password

secrets:
  code_password:
    file: ./code_password.txt

volumes:
  certs:
    name: certs
    external: true
  sync:
    external: true

networks:
  default:
    external:
      name: proxy