# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json

http:
  routers:
    bifrost:
      service: bifrost
      entryPoints:
        - websecure
      rule: "Host(`bifrost.tobyvin.com`)"

  services:
    bifrost:
      loadBalancer:
        servers:
          - url: "http://bifrost"
