# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json

http:
  routers:
    pihole:
      service: pihole
      entryPoints:
        - websecure
      rule: "Host(`pihole.tobyvin.com`)"

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://pi.hole"
