# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json

http:
  routers:
    portainer:
      service: portainer
      entryPoints:
        - websecure
      rule: "Host(`portainer.tobyvin.com`)"

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
