version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/www:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      
networks:
  default:
    external:
      name: proxy