version: "3.2"

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    hostname: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - agent
      - proxy
    volumes:
      - nfs:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  agent:
    external:
      name: agent
  proxy:
    external:
      name: proxy

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=bifrost,nolock,soft,rw
      device: ":/mnt/share/docker/portainer"
