version: "2.1"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./data:/config
      - ${HOME}/Sync:/config/Sync
      - ${HOME}/docker:/config/docker
      - ${HOME}/dotfiles:/config/dotfiles
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.syncthing.rule=(HostRegexp(`sync.${DOMAIN}.com`) && Path(`/{{.Node.Hostname}}`))"
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.services.syncthing.loadbalancer.server.port=8384

networks:
  default:
    external:
      name: proxy