version: "3"

services:
  viz:
    image: alexellis2/visualizer-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
          - node.platform.arch==armv7l

networks:
  default:
    driver: overlay
    external:
      name: proxy
